# Config of data used for testing.
#
# Chien-Hsiang Hsu, 2019.05.02



####################################################################################################
# TEST config
####################################################################################################
test_data: 
  name: 2019028023_PC9_A549_with_nuclear_marker
  file_type: '*.png'
  filter_patter: null

test_read_cfg :
  channels: 1
  dtype: uint8 
  crop_bd_width: 0
  resize: [1024, 1408]
  scale: 1/255.

chunk_size: 100 # number of images to predict each time (memory issue)
show_ans: True