# Config for segmenting nucleus using IncuCyte phase images
# 4-layered, W0 = 10, SGD
# No cropping in validation.
#
# Chien-Hsiang Hsu, 2019.05.06


model_name: ic_nuc_paper


####################################################################################################
# Training data
####################################################################################################
train_data: '2019028023_PC9_A549_with_nuclear_marker'
img_file_pattern: '*.png'
mask_file_pattern: '*.png' 
match_pattern: '_[A-Z]([4]|10)_'

# Used in tensorflow to load data
read_cfg :
  channels: 1
  dtype: uint8   
  resize: [1024, 1408]
  crop_bd_width: 0
  scale: 1/255.

test_size: 0.2
random_state: 423


####################################################################################################
# Dataset config
####################################################################################################
# training dataset
train_cfg:
  crop_size: [512, 512]
  to_flip: True

# validation dataset
val_cfg:
  crop_size: [512, 512]

batch_size: 5


####################################################################################################
# Model config
####################################################################################################
num_filters_list: [64, 128, 256, 512]
n_classes: 2


####################################################################################################
# TRAIN config
####################################################################################################
# weight config
w_cfg:
  w0: 15
  sigma: 5

loss_fn_name: weighted_bce
optimizer: tf.keras.optimizers.Adam(learning_rate=1e-4)
metrics: [u_net.dice_loss]
monitor: val_dice_loss
epochs: 50


####################################################################################################
# EVAL config
####################################################################################################
n_eval: 5


